# wrangler.toml

name = "streamlit_zgyd_worker"
main = "worker/index.js"
compatibility_date = "2024-01-01" 

# =========================================================================
# Cron Triggers - 必须与 worker/index.js 中的映射表匹配
# =========================================================================
[triggers]
crons = [
  "0 19 * * 7",
    # cleaner.yml             每周日一次
    # UTC: 每周日 19:00
    # CST: 每周一 03:00
  "0 22 * * *",
    # scheduler.yml (TASK_1)  每日一次
    # UTC: 每日 22:00
    # CST: 每日 06:00
  "10 2,6,10,14,18,22 * * *",
    # scheduler.yml (TASK_2)  每 4 小时一次
    # UTC: 02:10, 06:10, 10:10, 14:10, 18:10,       22:10
    # CST: 10:10, 14:10, 18:10, 22:10, 02:10 (次日), 06:10 (次日)
  "15,45 0-15,22-23 * * *",
    # scheduler.yml (TASK_3)  每 30 分钟一次 (限时段)
    # UTC: 00:00-15:59       和 22:00-23:59       (每小时的 15/45 分钟)
    # CST: 08:00-23:59 (当日) 和 06:00-07:59 (次日) (每小时的 15/45 分钟)
]

# =========================================================================
# Worker 运行时环境变量 (非敏感信息)
# =========================================================================
[vars]
GITHUB_OWNER = "I-m-PhD"
GITHUB_REPO = "streamlit_zgyd"
TARGET_BRANCH = "main"