name: Clean Up Old Workflow Runs

on:
  workflow_dispatch: # 允许手动运行
  schedule:
    # 每周一 UTC 00:00 (CST 08:00) 运行一次清理任务
    - cron: '0 0 * * 1'

permissions:
  contents: none
  actions: write # 必须具有删除 runs 的权限

jobs:
  delete_runs:
    name: Delete Old Runs
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          # 必须使用具有 'workflow' 范围的 PAT 或 GITHUB_TOKEN 并授予 'actions: write' 权限
          token: ${{ secrets.GITHUB_TOKEN }}
          # 仅保留最近 7 天的运行记录
          retain_days: 0
          # 每个工作流最少保留的运行次数
          keep_minimum_runs: 0