# .github/workflows/cleaner.yml

name: Remove Old Runs

on:
  workflow_dispatch: # 允许手动运行
  schedule:
    # 每周日一次
    - cron: '0 19 * * 6'

permissions:
  contents: none
  actions: write # 必须具有删除 runs 的权限

jobs:
  delete_runs:
    name: Delete Old Runs
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          # 必须使用具有 'workflow' 范围的 PAT 或 GITHUB_TOKEN 并授予 'actions: write' 权限
          token: ${{ secrets.GITHUB_TOKEN }}
          # 仅保留最近 1 天的运行记录
          retain_days: 0
          # 每个工作流最少保留 3 条运行记录
          keep_minimum_runs: 0