# .github/workflows/cloudflare.yml

name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main  
    paths:
      - 'worker/**'     # 监控 Worker 脚本文件夹, Worker 的核心逻辑代码
      - 'wrangler.toml' # 监控 Worker 配置文件, 包含 Worker 的 Cron 表达式
      - 'package.json'  # 监控 package.json 文件, 包含 Wrangler CLI 的版本
      - '.github/workflows/cloudflare.yml'  # 监控工作流文件本身
  workflow_dispatch:    # 允许手动触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Worker and Inject Secrets
        uses: cloudflare/wrangler-action@v3
        with:
          # 认证信息来自 GitHub Secrets
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # 告诉 Wrangler 配置文件在根目录
          workingDirectory: ./
          
          # 安全注入 Worker 运行时的 Secrets
          secrets: |
            WORKER_GITHUB_PAT