# .github/workflows/scheduler.yml
# 最终版本：使用 Composite Action 避免重复代码，实现最高可靠性。

name: Scheduled Data Crawler - Modular

on:
  # 允许手动触发所有任务
  workflow_dispatch:
    inputs:
      task_to_run:
        description: 'Select the task to run manually'
        required: true
        type: choice
        default: 'TASK_1'
        options:
          - TASK_1
          - TASK_2
          - TASK_3

  # T1: 每天 00:00 CST (UTC 16:00)
  schedule:
    - cron: '0 16 * * *'

    # T2: 每天 00:05, 12:05 CST (UTC 04:05, 16:05) - 错开 T1 5分钟
    - cron: '5 4,16 * * *'

    # T3: 每小时 10, 40 分 CST (UTC 10/40 分) - 避开所有关键提交点
    - cron: '10,40 * * * *'

permissions:
  contents: write # 授予写入权限用于提交数据

jobs:
  # ----------------------------------------------------
  # T1: 任务 1 Job 定义
  # ----------------------------------------------------
  run_task_1:
    name: "TASK 1: 所有招采 (00:00 CST)"
    runs-on: ubuntu-latest
    # 只有在 T1 的 cron 时间触发，或者手动选择 T1 时运行
    if: |
      github.event_name == 'workflow_dispatch' && github.event.inputs.task_to_run == 'TASK_1' || 
      github.event.schedule == '0 16 * * *'

    steps:
      # 调用组合操作，传入 task_name
      - name: Execute Composite Action for TASK_1
        uses: ./.github/actions/setup-commit-crawler
        with:
          task_name: TASK_1

  # ----------------------------------------------------
  # T2: 任务 2 Job 定义
  # ----------------------------------------------------
  run_task_2:
    name: "TASK 2: 正在招标 (00:05/12:05 CST)"
    runs-on: ubuntu-latest
    # 使用 contains 检查是否包含 T2 的两个 cron 表达式
    if: |
      github.event_name == 'workflow_dispatch' && github.event.inputs.task_to_run == 'TASK_2' || 
      contains(github.event.schedule, '5 4,16 * * *')

    steps:
      - name: Execute Composite Action for TASK_2
        uses: ./.github/actions/setup-commit-crawler
        with:
          task_name: TASK_2

  # ----------------------------------------------------
  # T3: 任务 3 Job 定义
  # ----------------------------------------------------
  run_task_3:
    name: "TASK 3: 正在招标_北京 (每小时 10/40 分 CST)"
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' && github.event.inputs.task_to_run == 'TASK_3' || 
      github.event.schedule == '10,40 * * * *'

    steps:
      - name: Execute Composite Action for TASK_3
        uses: ./.github/actions/setup-commit-crawler
        with:
          task_name: TASK_3