# .github/workflows/scheduler.yml

name: Scheduled Crawler

on:
  # ----------------------------------------------------
  # 核心修改：移除原生的 'schedule' 触发器。
  # Cloudflare Worker 将通过下面的 'workflow_dispatch' 触发器来替代它。
  # ----------------------------------------------------
  workflow_dispatch:
    inputs:
      # 此名称必须与 worker/index.js 中传递的参数名一致
      task_to_run:
        description: 'Scheduled Task ID (TASK_1, TASK_2, or TASK_3) or Manual Run'
        required: true
        type: choice
        default: 'TASK_1'
        options:
          - TASK_1
          - TASK_2
          - TASK_3

permissions:
  contents: write # 授予写入权限用于提交数据 (用于 git-auto-commit-action)

jobs:
  # ----------------------------------------------------
  # T1: 任务 1 Job 定义 (每日 06:00 CST)
  # ----------------------------------------------------
  run_task_1:
    name: "TASK 1: 所有招采"
    runs-on: ubuntu-latest
    # 核心修改：if 条件现在仅依赖 workflow_dispatch 传入的参数。
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.task_to_run == 'TASK_1'

    steps:
      - name: Checkout code for Local Action Access
        uses: actions/checkout@v5

      - name: Execute Composite Action for TASK_1
        uses: ./.github/actions/sop
        with:
          task_name: TASK_1

  # ----------------------------------------------------
  # T2: 任务 2 Job 定义 (每 4 小时一次)
  # ----------------------------------------------------
  run_task_2:
    name: "TASK 2: 正在招标"
    runs-on: ubuntu-latest
    # 核心修改：if 条件现在仅依赖 workflow_dispatch 传入的参数。
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.task_to_run == 'TASK_2'

    steps:
      - name: Checkout code for Local Action Access
        uses: actions/checkout@v5

      - name: Execute Composite Action for TASK_2
        uses: ./.github/actions/sop
        with:
          task_name: TASK_2

  # ----------------------------------------------------
  # T3: 任务 3 Job 定义 (每 30 分钟一次)
  # ----------------------------------------------------
  run_task_3:
    name: "TASK 3: 正在招标_北京"
    runs-on: ubuntu-latest
    # 核心修改：if 条件现在仅依赖 workflow_dispatch 传入的参数。
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.task_to_run == 'TASK_3'

    steps:
      - name: Checkout code for Local Action Access
        uses: actions/checkout@v5

      - name: Execute Composite Action for TASK_3
        uses: ./.github/actions/sop
        with:
          task_name: TASK_3