name: Scheduled Crawler

on:
  # 允许手动触发所有任务
  workflow_dispatch:
    inputs:
      task_to_run:
        description: 'Select the task to run manually'
        required: true
        type: choice
        default: 'TASK_1'
        options:
          - TASK_1
          - TASK_2
          - TASK_3
  
  # T1: 每天 00:00 CST (UTC 16:00)
  schedule:
    - cron: '0 16 * * *'

    # T2: 每天 00:10, 12:10 CST (UTC 04:10, 16:10) - 为 T1 预留 10 分钟
    - cron: '10 4,16 * * *'

    # T3: 每小时 20, 50 分 CST (UTC 20/50 分) - 避开所有关键提交点
    - cron: '20,50 * * * *'

permissions:
  contents: write # 授予写入权限用于提交数据 (用于 git-auto-commit-action)

jobs:
  # ----------------------------------------------------
  # T1: 任务 1 Job 定义
  # ----------------------------------------------------
  run_task_1:
    name: "TASK 1: 所有招采 (00:00 CST)"
    runs-on: ubuntu-latest
    # 使用括号确保逻辑优先级正确，并使用精确匹配防止跳过
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.task_to_run == 'TASK_1') || 
      (github.event.schedule == '0 16 * * *')

    steps:
      # 关键：先检出代码，确保本地 Composite Action 可访问
      - name: Checkout code for Local Action Access
        uses: actions/checkout@v4

      - name: Execute Composite Action for TASK_1
        uses: ./.github/actions/setup-commit-crawler
        with:
          task_name: TASK_1
          github_token: ${{ secrets.GITHUB_TOKEN }} # 传递 token

  # ----------------------------------------------------
  # T2: 任务 2 Job 定义
  # ----------------------------------------------------
  run_task_2:
    name: "TASK 2: 正在招标 (00:10/12:10 CST)"
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.task_to_run == 'TASK_2') || 
      (github.event.schedule == '10 4 * * *') || 
      (github.event.schedule == '10 16 * * *')

    steps:
      - name: Checkout code for Local Action Access
        uses: actions/checkout@v4

      - name: Execute Composite Action for TASK_2
        uses: ./.github/actions/setup-commit-crawler
        with:
          task_name: TASK_2
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # ----------------------------------------------------
  # T3: 任务 3 Job 定义
  # ----------------------------------------------------
  run_task_3:
    name: "TASK 3: 正在招标_北京 (每小时 20/50 分 CST)"
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.task_to_run == 'TASK_3') || 
      (github.event.schedule == '20 * * * *') || 
      (github.event.schedule == '50 * * * *')

    steps:
      - name: Checkout code for Local Action Access
        uses: actions/checkout@v4

      - name: Execute Composite Action for TASK_3
        uses: ./.github/actions/setup-commit-crawler
        with:
          task_name: TASK_3
          github_token: ${{ secrets.GITHUB_TOKEN }}